childBlocks: null
field: e4bfa0ac-3130-4cb4-b1e7-164e36011877 # Page builder
fieldLayouts:
  17f816c8-ce29-41d9-a513-99f40b033185:
    tabs:
      -
        elements:
          -
            fieldUid: 2ddcf913-a91b-466b-8554-88841a39720a # Redactor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Tekst
        sortOrder: 1
group: 9bb9a1e4-c6e3-462e-9837-a36078342104 # Blokken
handle: blockRedactor
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Tekst
sortOrder: 4
topLevel: false
