columnSuffix: null
contentColumnType: string
fieldGroup: 5b9ea4eb-4ef4-4d3f-9167-f255e7352c2a # Blocks
handle: pageBuilder
instructions: ''
name: 'Page builder'
searchable: false
settings:
  maxBlocks: ''
  maxLevels: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
  wasModified: false
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
